### ISSUE TITLE
Issues with SimG4FullSimDCHRegion

### ISSUE THREAD

**Issue by jmcarcell** [HEP-FCC/k4SimGeant4#34]
I was compiling on Alma 9 and got the following error:
```
==> Error: ProcessError: Command exited with status 2:
    '/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-04/x86_64-almalinux9-gcc11.3.1-opt/gmake/4.4.1-u7jilx/bin/make' '-j8'

3 errors found in build log:
     343    #10 0x0000000000439bd4 in SmartIF<IProperty>::reset (ptr=0x0, this=0x7ffc2b91
            d390) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2in
            qzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/SmartIF.h:98
     344    #11 configGenerator::genConfig (this=0x7ffc2b91e2e0, libs=..., userModule="")
             at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5e
            nmwtu/spack-src/GaudiKernel/src/Util/genconf.cpp:571
     345    #12 0x000000000042ee74 in main (argc=<optimized out>, argv=<optimized out>) a
            t /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enm
            wtu/spack-src/GaudiKernel/src/Util/genconf.cpp:408
     346    ===========================================================
     347    
     348    
  >> 349    make[2]: *** [SimG4Full/CMakeFiles/SimG4FullPlugins.dir/build.make:235: SimG4
            Full/libSimG4FullPlugins.so] Error 139
     350    make[2]: *** Deleting file 'SimG4Full/libSimG4FullPlugins.so'
     351    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-k4simgeant4-621
            606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid
            6/spack-build-kfbhhnd'
  >> 352    make[1]: *** [CMakeFiles/Makefile2:535: SimG4Full/CMakeFiles/SimG4FullPlugins
            .dir/all] Error 2
     353    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-k4simgeant4-621
            606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid
            6/spack-build-kfbhhnd'
  >> 354    make: *** [Makefile:139: all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-out.txt
```

The traceback points to the destructor of `SimG4FullSimDCHRegion` (it's all the information that you can get from the traceback, I could probably reproduce but I don't have it anymore...) and this line looks very suspicious with a naked delete:
https://github.com/HEP-FCC/k4SimGeant4/blob/main/SimG4Full/src/components/SimG4FullSimDCHRegion.cpp#L23

I have compiled successfully on Centos 7 and Ubuntu 22.04 this repo in the last days so it's also a bit weird that I only saw this in Alma 9.

**Comment by andresailer** [comment]
Can you post the traceback as well? (Or am I being blind, and it is already in the post above?)

**Comment by jmcarcell** [comment]
It only tells that it's happening in the destructor
```
===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fbe5863119a in wait4 () from /lib64/libc.so.6
#1  0x00007fbe5857a8fb in do_system () from /lib64/libc.so.6
#2  0x00007fbe58ee7ab5 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0xc4d8e0) at /tmp/root/spack-stage/spack-stage-root-6.26.10-5ga7ljtlv65ov5g6t5gceewcfllz6q6t/spack-src/core/unix/src/TUnixSystem.cxx:2104
#3  TUnixSystem::StackTrace (this=0xc4d8e0) at /tmp/root/spack-stage/spack-stage-root-6.26.10-5ga7ljtlv65ov5g6t5gceewcfllz6q6t/spack-src/core/unix/src/TUnixSystem.cxx:2395
#4  0x00007fbe58ee5245 in TUnixSystem::DispatchSignals (this=0xc4d8e0, sig=kSigSegmentationViolation) at /tmp/root/spack-stage/spack-stage-root-6.26.10-5ga7ljtlv65ov5g6t5gceewcfllz6q6t/spack-src/core/unix/src/TUnixSystem.cxx:3615
#5  <signal handler called>
#6  0x00007fbe46d0261a in SimG4FullSimDCHRegion::~SimG4FullSimDCHRegion() () from /tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd/SimG4Full/libSimG4FullPlugins.so
#7  0x00007fbe46d028a9 in SimG4FullSimDCHRegion::~SimG4FullSimDCHRegion() () from /tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd/SimG4Full/libSimG4FullPlugins.so
#8  0x00007fbe5948b632 in implements<IAlgTool, IDataHandleHolder, IProperty, IStateful>::release (this=0x230d390) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/implements.h:53
#9  implements<IAlgTool, IDataHandleHolder, IProperty, IStateful>::release (this=0x230d390) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/implements.h:50
#10 0x0000000000439bd4 in SmartIF<IProperty>::reset (ptr=0x0, this=0x7ffc97a85e80) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/SmartIF.h:98
#11 configGenerator::genConfig (this=0x7ffc97a86dd0, libs=..., userModule="") at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/src/Util/genconf.cpp:571
#12 0x000000000042ee74 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/src/Util/genconf.cpp:408
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007fbe46d0261a in SimG4FullSimDCHRegion::~SimG4FullSimDCHRegion() () from /tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd/SimG4Full/libSimG4FullPlugins.so
#7  0x00007fbe46d028a9 in SimG4FullSimDCHRegion::~SimG4FullSimDCHRegion() () from /tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd/SimG4Full/libSimG4FullPlugins.so
#8  0x00007fbe5948b632 in implements<IAlgTool, IDataHandleHolder, IProperty, IStateful>::release (this=0x230d390) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/implements.h:53
#9  implements<IAlgTool, IDataHandleHolder, IProperty, IStateful>::release (this=0x230d390) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/implements.h:50
#10 0x0000000000439bd4 in SmartIF<IProperty>::reset (ptr=0x0, this=0x7ffc97a85e80) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/include/GaudiKernel/SmartIF.h:98
#11 configGenerator::genConfig (this=0x7ffc97a86dd0, libs=..., userModule="") at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/src/Util/genconf.cpp:571
#12 0x000000000042ee74 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/root/spack-stage/spack-stage-gaudi-36.10-36vhs6gxxh4hfm3vmnl2inqzw5enmwtu/spack-src/GaudiKernel/src/Util/genconf.cpp:408
===========================================================


make[2]: *** [SimG4Full/CMakeFiles/SimG4FullPlugins.dir/build.make:235: SimG4Full/libSimG4FullPlugins.so] Error 139
make[2]: *** Deleting file 'SimG4Full/libSimG4FullPlugins.so'
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd'
make[1]: *** [CMakeFiles/Makefile2:535: SimG4Full/CMakeFiles/SimG4FullPlugins.dir/all] Error 2
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-k4simgeant4-621606e5f3a49751f29fe30254bc1c073a81c7e6=develop-kfbhhnde54tsxpnancyeifm5vdystid6/spack-build-kfbhhnd'
make: *** [Makefile:139: all] Error 2
```
